version: "3"
services:
  developing:
    build: containers/developing
    volumes:
      - .:/var/app
  php_8_0_test:
    build: containers/run_php_8_0_tests
    volumes:
      - .:/var/app
  php_8_1_test:
    build: containers/run_php_8_1_tests
    volumes:
      - .:/var/app
  phpcs:
    build: containers/run_php_codesniffer
    volumes:
      - .:/var/app

