name: Tests
on: [push, pull_request]

jobs:
  unit_tests_8_0:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Perform phpunit tests
        uses: ./containers/run_php_8_0_tests
  unit_tests_8_1:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Perform phpunit tests
        uses: ./containers/run_php_8_1_tests
  code_style:
    name: Code Style Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Analyze code style
        uses: ./containers/run_php_codesniffer